export const suggestionList = [
    "Bride",
    "Bride + Father",
    "Bride + Mother",
    "Bride + Bride’s parents",
    "Bride + Bride’s immediate family",
    "Bride + Sisters",
    "Bride + Brothers",
    "Bride + Mother + Sister",
    "Bride + Mother + Sister + Grandmother",
    "Bride + GrandmotherBride + Grandfather",
    "Bride + Bride’s grandparents",
    "Bride + Mother + Mother-in-Law",
    "Bride + Mother-in-Law",
    "Bride + Mother-in-Law + Groom’s sisters + Groom’s Grandmother",
    "Bride + Groom’s sisters",           
    "Bride + Bridesmaids",
    "Bride + each Bridesmaid",
    "Bride + Flower girls ",
    "Groom",
    "Groom + Mother",
    "Groom + Father",
    "Groom + Groom’s parents",
    "Groom + Groom’s immediate family",
    "Groom + Sisters",
    "Groom + Brothers",
    "Groom + Father + Brothers",
    "Groom + Father + Brothers + Grandfather",
    "Groom + Grandmother",
    "Groom + Grandfather",
    "Groom + Groom’s grandparents",
    "Groom + Mother + Mother-in-Law",
    "Groom + Mother-in-LawGroom + Sister-in-Law",
    "Groom + Groomsmen",
    "Groom + each Groomsman",
    "Bride + Groom + Groom’s parents",
    "Bride + Groom + Both sets of parents",
    "Bride + Groom + All grandparents",
    "Bride + Groom + Bride’s grandparents",
    "Bride + Groom + Groom’s grandparents",
    "Bride + Groom + Siblings",
    "Bride + Groom + Officiant",
    "Bride + Groom + Groom’s immediate family w/ grandparents",
    "Bride + Groom + Bride’s immediate family w/ grandparents",
    "Bride + Groom + Both families w/ grandparents",
    "Bride + Groom + Groom’s immediate family w/sibling’s spouses",
    "Bride + Groom + Bride’s immediate family w/sibling’s spouses",
    "Bride + Groom + Both immediate family w/sibling’s spouses",
    "Bride + Groom + Wedding party",
    "Bride + Groom + Maid of honor + Best man",
    "Bride + Groom + Flower Girl + Ring Bearer"
    ];
    